name: DEV CI/CD

on:
  push:
    branches: [main]

jobs:
  build-test:
    name: Build 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: 8
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test -- --watchAll=false

      - name: Build
        run: pnpm build
