name: DEV CI/CD

on:
  push:
    branches: [main]

jobs:
  build-test:
    name: Build 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@8 --activate

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test -- --watchAll=false

      - name: Build
        run: pnpm build
