name: DEV CI/CD

on:
  push:
    branches: [main]

jobs:
  build-test:
    name: Build 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug
        run: ls -la pnpm-lock.yaml

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: 9.5.0
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Cache pnpm store
        uses: actions/cache@v4
        with: 
          path: ~/.local/share/pnpm/store/v3
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-key: | 
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        run: pnpm test

      - name: Cache Build
        uses: actions/cache@v4
        with:
          path: dist
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build
        run: pnpm build
